### PR TITLE
Upgrade to `django-ninja` v1 / `pydantic` v2

### PR DESCRIPTION
**Pull request by mvandenburgh**
This is a major upgrade that requires changes to many of our Pydantic-based schemas. See https://docs.pydantic.dev/latest/migration/.

A lot of the changes in this PR were automated by the [`bump-pydantic`](https://docs.pydantic.dev/latest/migration/#code-transformation-tool) tool, with some manual cleanup and fixes after.

Note, pydantic 2 also claims backwards compatibility with pydantic 1 code via the nested [`pydantic.v1`](https://docs.pydantic.dev/2.9/migration/#continue-using-pydantic-v1-features) package. However, `django-ninja` does not support it so we can not use it here.

### CODE REVIEW

**Comment by mvandenburgh** [comment]
@BryonLewis @floryst this is ready for review. I tried testing the entire feature set of the application with these changes, and I fixed all the issues I came across. But, it's very possible that I missed something considering the scope of changes, so any further stress testing of the whole system would welcome :slightly_smiling_face:

Also, I would suggest we postpone merging this PR until v1.14, so no particular urgency here.

**Review by BryonLewis — COMMENTED** [review]
Most things involving the endpoints touched seemed to work properly including downloading and the downloading stats.

Not approval yet but just a checklist of things I went over:

- Scoring - image fetching and visualization for WV and S2
- Scoring - visualization of Sites/Observations, Scoring Mode
- Scoring - Selection of site and downloading of Animations

- RGD - image fetching and visualization in map for WV and S2
- RGD - Site/Observation vector tile visualization
- RGD - Selection of objects and exporting animations
- RGD - Downloading JSON file


Not Working:

- Image Browser in both RGD and Scoring - I think a merge to main will fix it.  Forrest I believe fixed a CSS issue for this
- Scrolling the ModelRun list - I believe this again is a merge from main that will fix it.

**Review by BryonLewis — APPROVED** [review]
after the merge from main I believe the remaining issues I had are now fixed.

**Comment by mvandenburgh** [comment]
Closing after discussing with @aashish24. We might revisit this in the future

**Pull request closed without merging**
