### PR TITLE
Upgrade `Pillow` + `poetry`, remove unused dependencies

### PR DESCRIPTION
**Pull request by mvandenburgh**
Depends on #368

### CODE REVIEW

**Comment by mvandenburgh** [comment]
The API changes made to Pillow don't affect our usage of it from what I can tell, so my commend in #368 about that was wrong.

**Comment by mvandenburgh** [comment]
I'll rebase this one on `main` to get rid of the extra commits.

**Comment by mvandenburgh** [comment]
Ok, this is all set now.

**Review by BryonLewis — APPROVED** [review]
:+1

**Pull request merged**
