### PR TITLE
Enabling point hover and selection

### PR DESCRIPTION
**Pull request by BryonLewis**
- Swaps the endpoints for vector tiles to properly use the UUID as the `id` field.  This is needed for hovering and selection
- Adds point selection/hovering to the mouseEvents.ts for sites specifically.
- Sites have their radius change on hovering instead of the outline.
- The point status was utilizing `status_annotated` but in my testing with the metric/scoring code there was a separate indicator called `point_status` that I switched it to.  This provides some proper status for the ground truth.

### CODE REVIEW

**Comment by mvandenburgh** [comment]
The new `/details` endpoint was 404'ing due to missing a trailing slash in the scoring app only, I pushed a commit to fix that.

I'm also encountering an issue in the scoring view when I try to view vector tiles for a model run with point annotations. Toggling the model run "on" doesn't render any vector tiles, and in the browser dev console I see this

```
Error: layers[95]: source "vectorTileRegionSource_-1" not found
```

@BryonLewis does that make any immediate sense to you?

**Comment by BryonLewis** [comment]
> @BryonLewis does that make any immediate sense to you?

Yeah, sorry about that.
The main issue is that RDWATCH handles regions differently than scoring and I forgot to guard against some stuff in the Scoring mode.

I had blocked the vectorTileRegionSource in the building of the source filter: https://github.com/ResonantGeoData/RD-WATCH/blob/main/vue/src/mapstyle/rdwatchtiles.ts#L277-L286

But I forgot to do it in the filter for the for the tiles:
https://github.com/ResonantGeoData/RD-WATCH/blob/main/vue/src/mapstyle/rdwatchtiles.ts#L427-L437

The commit I just pushed guards this from being added unless we are in the scoring endpoint.

**Comment by mvandenburgh** [comment]
@BryonLewis in scoring mode, I get this server error on the vector tile endpoint with the latest commit:

```
[11/Jul/2024 14:25:58] "GET /api/scoring/model-runs/a9c8e330-1802-4940-81d1-867eded18399/vector-tile/11/1758/792.pbf/? HTTP/1.1" 500 4076
Cannot resolve keyword 'site_truth' into field. Choices are: activity_type, associated, association_status, central_spatial_distance_threshold, central_temporal_distance_threshold, color_code, evaluation_run_uuid, evaluation_run_uuid_id, id, max_spatial_distance_threshold, max_temporal_distance_threshold, min_area, min_confidence_score, min_spatial_distance_threshold, min_temporal_distance_threshold, rho, site_proposal, site_proposal_area, site_truth_matched, site_truth_matched_count, tau
Traceback (most recent call last):
  File "/home/local/KHQ/michael.vandenburgh/.cache/pypoetry/virtualenvs/rdwatch-nKCMUNfY-py3.11/lib/python3.11/site-packages/ninja/operation.py", line 104, in run
    result = self.view_func(request, **values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/KHQ/michael.vandenburgh/Desktop/smart/RD-WATCH/rdwatch/scoring/views/vector_tile.py", line 758, in vector_tile
    EvaluationBroadAreaSearchProposal.objects.filter(
  File "/home/local/KHQ/michael.vandenburgh/.cache/pypoetry/virtualenvs/rdwatch-nKCMUNfY-py3.11/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/KHQ/michael.vandenburgh/.cache/pypoetry/virtualenvs/rdwatch-nKCMUNfY-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/KHQ/michael.vandenburgh/.cache/pypoetry/virtualenvs/rdwatch-nKCMUNfY-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/local/KHQ/michael.vandenburgh/.cache/pypoetry/virtualenvs/rdwatch-nKCMUNfY-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/local/KHQ/michael.vandenburgh/.cache/pypoetry/virtualenvs/rdwatch-nKCMUNfY-py3.11/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/KHQ/michael.vandenburgh/.cache/pypoetry/virtualenvs/rdwatch-nKCMUNfY-py3.11/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/local/KHQ/michael.vandenburgh/.cache/pypoetry/virtualenvs/rdwatch-nKCMUNfY-py3.11/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1472, in build_filter
    return self._add_q(
           ^^^^^^^^^^^^
  File "/home/local/KHQ/michael.vandenburgh/.cache/pypoetry/virtualenvs/rdwatch-nKCMUNfY-py3.11/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/local/KHQ/michael.vandenburgh/.cache/pypoetry/virtualenvs/rdwatch-nKCMUNfY-py3.11/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/KHQ/michael.vandenburgh/.cache/pypoetry/virtualenvs/rdwatch-nKCMUNfY-py3.11/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/KHQ/michael.vandenburgh/.cache/pypoetry/virtualenvs/rdwatch-nKCMUNfY-py3.11/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'site_truth' into field. Choices are: activity_type, associated, association_status, central_spatial_distance_threshold, central_temporal_distance_threshold, color_code, evaluation_run_uuid, evaluation_run_uuid_id, id, max_spatial_distance_threshold, max_temporal_distance_threshold, min_area, min_confidence_score, min_spatial_distance_threshold, min_temporal_distance_threshold, rho, site_proposal, site_proposal_area, site_truth_matched, site_truth_matched_count, tau
```

Do you see that as well?

**Comment by BryonLewis** [comment]
> Do you see that as well?

I don't but you probably have different data you scored against which is a good thing because it brought up this error.  I had copied over the text, assuming both the EvaluationBroadAreaSearchDeteciton and EvaluationBroadAreaSearchProposal had the same issue with the names but they don't.  So hopefully that last commit should fix that problem.

**Review by mvandenburgh — APPROVED** [review]

**Pull request merged**
