### PR TITLE
Treat post_stac as "get or create"

### PR DESCRIPTION
**Pull request by banesullivan**
Related: 
- https://github.com/ResonantGeoData/ResonantGeoData/pull/633
- https://github.com/ResonantGeoData/ResonantGeoData/issues/629

### CODE REVIEW

**Comment by AlmightyYakob** [comment]
Relies on client work to be implemented in https://github.com/ResonantGeoData/ResonantGeoData/pull/633, specifically in `create_file_from_url`. Once that's done, we can update the client version, and merge this.

**Comment by banesullivan** [comment]
@AlmightyYakob, I think we need a fitler on STACFile to do the same check (see if a STACFile exists for the given ChecsumFile ID).

**Comment by AlmightyYakob** [comment]
> @AlmightyYakob, I think we need a fitler on STACFile to do the same check (see if a STACFile exists for the given ChecsumFile ID).

You're right, I'll add that.

**Comment by AlmightyYakob** [comment]
@banesullivan I've added that, so once that upstream PR is merged and incorporated here, that failing test should pass. Also, even though I've used the `swagger_auto_schema` decorator, the swagger page doesn't show the `file` field in the endpoint for stac file listing. I'm not sure why this is, but figured it shouldn't block this PR.

**Pull request merged**
